services:
  hsm-be-core-auth:
    image: hsm-be-core-auth:latest
    build:
      context: ../../../../../hsm-be-core-auth
      dockerfile: Dockerfile.dev
    container_name: hsm-be-core-auth
    networks:
      - hsm-backend-network
    volumes:
      - ../../../../../hsm-be-core-auth:/app
      - /app/node_modules
    env_file:
      - ../../../../.env
    environment:
      SECRET_PATH: /be/core/auth
      LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
    restart: unless-stopped