services:
  hsm-be-core-coms:
    image: hsm-be-core-coms:latest
    build:
      context: ../../../../../hsm-be-core-coms
      dockerfile: Dockerfile.dev
    container_name: hsm-be-core-coms
    networks:
      - hsm-backend-network
    volumes:
      - ../../../../../hsm-be-core-coms:/app
      - /app/node_modules
    env_file:
      - ../../../../.env
    environment:
      SECRET_PATH: /be/core/coms
      LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
    restart: unless-stopped
