services:
  hsm-be-core-users:
    image: hsm-be-core-users:latest
    build:
      context: ../../../../../hsm-be-core-users
      dockerfile: Dockerfile.dev
    container_name: hsm-be-core-users
    networks:
      - hsm-backend-network
    volumes:
      - ../../../../../hsm-be-core-users:/app
      - /app/node_modules
    env_file:
      - ../../../../.env
    environment:
      SECRET_PATH: /be/core/users
      LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
    restart: unless-stopped