services:
  hsm-be-has-cob-gdp-transaccion:
      image: hsm-be-has-cob-gdp-transaccion:latest
      build:
        context: ../../../../../../../hsm-be-has-cob-gdp-transaccion
        dockerfile: Dockerfile.dev
      container_name: hsm-be-has-cob-gdp-transaccion
      networks:
        - hsm-backend-network
      volumes:
        - ../../../../../../../hsm-be-has-cob-gdp-transaccion:/app
        - /app/node_modules
      env_file:
        - ../../../../../../.env
      environment:
        SECRET_PATH: /be/has/cob/gdp/transaccion
        LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
      restart: unless-stopped