services:
  hsm-be-has-gaa-gth-gsr-postulantes:
    image: hsm-be-has-gaa-gth-gsr-postulantes:latest
    build:
      context: ../../../../../../../../hsm-be-has-gaa-gth-gsr-postulantes
      dockerfile: Dockerfile.dev
    container_name: hsm-be-has-gaa-gth-gsr-postulantes
    networks:
      - hsm-backend-network
    volumes:
      - ../../../../../../../../hsm-be-has-gaa-gth-gsr-postulantes:/app
      - /app/node_modules
    env_file:
      - ../../../../../../../.env
    environment:
      SECRET_PATH: /be/has/gaa/gth/gsr/postulantes
      LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
    restart: unless-stopped
  